import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Clapperboard, Play, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

async function fetchGenre(): Promise<{ id: string; name: string }[]> {
	const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
		headers: {
			Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
		},
	});

	const data = await res.json();
	return data.genres;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const genres = await fetchGenre();

    const handleSearch = async function (form: FormData) {
        "use server";

        const q = form.get("q");
        redirect(`/search?q=${q}`);
    }

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header className="p-4 border-b flex justify-between items-center">
					<h1 className="text-3xl font-bold flex flex-row items-center gap-2">
						<Clapperboard />
						Movie App
					</h1>

					<form className="flex gap-2" action={handleSearch}>
						<Input placeholder="Search..." name="q" />
						<Button type="submit">
							<Search />
						</Button>
					</form>
				</header>
				<main className="flex flex-row">
					<nav className="w-50 p-4 border-r flex flex-col shrink-0 gap-1">
						<Button
							variant="outline"
							asChild>
							<Link
								href={"/"}
								className="justify-start py-5">
								<Play />
								All Movie
							</Link>
						</Button>
						{genres.map(genre => {
							return (
								<Button
									key={genre.id}
									variant="outline"
									asChild>
									<Link
										href={`/genre/${genre.name}/${genre.id}`}
										className="justify-start py-5">
										<Play />
										{genre.name}
									</Link>
								</Button>
							);
						})}
					</nav>
					<section className="p-4">{children}</section>
				</main>
			</body>
		</html>
	);
}
